### ISSUE TITLE
middleware session 问题

### ISSUE THREAD

**Issue by KevinsDeveloper** [vicanso/tiny-site#2]
middleware 目录下的 session 程序好像有错误.

middleware/session.go:39:3: unknown field 'CookieKeys' in struct literal of type session.Options
middleware/session.go:40:3: unknown field 'CookieMaxAge' in struct literal of type session.Options
middleware/session.go:41:3: unknown field 'CookiePath' in struct literal of type session.Options
middleware/session.go:46:22: too many arguments in call to session.New
        have (*http.Request, "github.com/kataras/iris/context".ResponseWriter, *session.Options)
        want (cookies.ReadWriter, *session.Options)
middleware/static_serve.go:150:9: assignment mismatch: 2 variables but 1 values

**Comment by vicanso** [comment]
@KevinsDeveloper 你是否用dep来安装依赖？

**Comment by KevinsDeveloper** [comment]
> @KevinsDeveloper你是否用DEP来安装依赖？

没有，没注意看到需要用dep来安装依赖，我直接go get的

**Comment by KevinsDeveloper** [comment]
> @KevinsDeveloper 你是否用dep来安装依赖？

用dep装完又有报错，请问怎么继续了？

# github.com/vicanso/tiny-site/vendor/github.com/kataras/iris/view
vendor/github.com/kataras/iris/view/django.go:225:27: pongo2.RegisterTag(tagName, fn) used as value
vendor/github.com/kataras/iris/view/django.go:253:19: undefined: pongo2.NewLocalFileSystemLoader
vendor/github.com/kataras/iris/view/django.go:258:22: too many arguments in call to pongo2.NewSet
vendor/github.com/kataras/iris/view/django.go:311:22: too many arguments in call to pongo2.NewSet
        have (string, *tDjangoAssetLoader)
        want (string)

**Comment by vicanso** [comment]
我重新clone一份新的，执行 `https_proxy=127.0.0.1:49356 http_proxy=127.0.0.1:49356 dep ensure` 之后，可以正常运行，所有module的版本如下：

```
PROJECT                                    CONSTRAINT        VERSION        REVISION  LATEST   PKGS USED
github.com/BurntSushi/toml                 v0.3.0            v0.3.0         b26d9c3   v0.3.0   1
github.com/Joker/jade                      branch master     branch master  8828253   82af6d9  1
github.com/Shopify/goreferrer              branch master     branch master  b9777dc   ec9c9a5  1
github.com/asaskevich/govalidator          ^9.0.0            v9             ccb8e96   v9       1
github.com/aymerick/raymond                branch master     branch master  b565731   b565731  4
github.com/bitly/go-simplejson             v0.5.0            v0.5.0         aabad6e   v0.5.0   1
github.com/eknkc/amber                     branch master     branch master  cdade1c   cdade1c  2
github.com/fatih/structs                   v1.0              v1.0           a720dfa   v1.0     1
github.com/flosch/pongo2                   branch master     branch master  24195e6   79872a7  1
github.com/fsnotify/fsnotify               v1.4.7            v1.4.7         c282820   v1.4.7   1
github.com/go-redis/redis                  ^6.13.2           v6.14.1        f3bba01   v6.15.1  8
github.com/gobuffalo/packr                 ^1.13.3           v1.13.5        6c8156e   v1.21.9  1
github.com/golang/protobuf                 v1.2.0            v1.2.0         aa810b6   v1.2.0   5
github.com/h2non/gock                      ^1.0.9            v1.0.10        db99161   v1.0.12  1
github.com/hashicorp/go-version            v1.0.0            v1.0.0         b5a281d   v1.0.0   1
github.com/hashicorp/golang-lru            ^0.5.0            v0.5.0         20f1fb7   v0.5.0   2
github.com/hashicorp/hcl                   v1.0.0            v1.0.0         8cb6e5b   v1.0.0   10
github.com/iris-contrib/formBinder         branch master     branch master  ad9fb86   fbd5963  1
github.com/iris-contrib/go.uuid            branch v2         branch v2      36e9d2e   36e9d2e  1
github.com/jinzhu/gorm                     ^1.9.1            v1.9.1         6ed508e   v1.9.2   2
github.com/jinzhu/inflection               branch master     branch master  0414036   0414036  1
github.com/json-iterator/go                1.1.5 (override)  1.1.5          1624edc   v1.1.5   1
github.com/juju/errors                     branch master     branch master  22422da   089d3ea  1
github.com/kataras/golog                   branch master     branch master  03be101   03be101  1
github.com/kataras/iris                    ^10.7.0           10.7.0         217d9fe   v10.7.1  26
github.com/kataras/pio                     branch master     branch master  a9733b5   ea782b3  2
github.com/kataras/survey                  branch v2         branch v2      00934ae   00934ae  3
github.com/klauspost/compress              v1.4.0            v1.4.0         b939724   v1.4.0   2
github.com/klauspost/cpuid                 v1.1              v1.1           ae7887d   v1.1     1
github.com/lib/pq                          ^1.0.0            v1.0.0         4ded0e9   v1.0.0   3
github.com/magiconair/properties           v1.8.0            v1.8.0         c235336   v1.8.0   1
github.com/mattn/go-colorable              v0.0.9            v0.0.9         167de6b   v0.0.9   1
github.com/mattn/go-isatty                 v0.0.4            v0.0.4         6ca4dbf   v0.0.4   1
github.com/mgutz/ansi                      branch master     branch master  9520e82   9520e82  1
github.com/microcosm-cc/bluemonday         branch master     branch master  82c7118   506f3da  1
github.com/mitchellh/mapstructure          v1.0.0            v1.0.0         fa473d1   v1.0.0   1
github.com/modern-go/concurrent            1.0.3             1.0.3          bacd9c7   1.0.3    1
github.com/modern-go/reflect2              1.0.1             1.0.1          4b7aa43   1.0.1    1
github.com/mozillazg/request               ^0.8.0            v0.8.0         052232e   v0.8.0   1
github.com/oklog/ulid                      ^1.0.0            v1.2.0         6276fb3   v1.3.1   1
github.com/pelletier/go-toml               v1.2.0            v1.2.0         c01d127   v1.2.0   1
github.com/pkg/errors                      v0.8.0            v0.8.0         645ef00   v0.8.0   1
github.com/ryanuber/columnize              branch master     branch master  abc9093   abc9093  1
github.com/shurcooL/sanitized_anchor_name  branch master     branch master  86672fc   7bfe4c7  1
github.com/spf13/afero                     v1.1.2            v1.1.2         d40851c   v1.1.2   2
github.com/spf13/cast                      v1.2.0            v1.2.0         8965335   v1.2.0   1
github.com/spf13/jwalterweatherman         v1.0.0            v1.0.0         4a4406e   v1.0.0   1
github.com/spf13/pflag                     v1.0.2            v1.0.2         9a97c10   v1.0.2   1
github.com/spf13/viper                     ^1.0.2            v1.2.0         8fb6420   v1.3.1   1
github.com/vicanso/cookies                 ^0.0.2            0.0.2          846aea2   0.0.2    1
github.com/vicanso/fresh                   ^0.0.2            0.0.2          9d7cefa   0.0.2    1
github.com/vicanso/keygrip                 0.0.1             0.0.1          c7f2aa0   0.0.1    1
github.com/vicanso/session                 ^0.0.6            0.0.6          8719544   0.0.8    1
github.com/vicanso/tiny                    branch master     branch master  cb00b1e   a16c589  1
go.uber.org/atomic                         v1.3.2            v1.3.2         1ea20fb   v1.3.2   1
go.uber.org/multierr                       v1.1.0            v1.1.0         3c49374   v1.1.0   1
go.uber.org/zap                            ^1.0.0-rc.1       v1.9.1         ff33455   v1.9.1   6
golang.org/x/crypto                        branch master     branch master  0e37d00   c7b33c3  2
golang.org/x/net                           branch master     branch master  26e67e7   d26f9f9  12
golang.org/x/sys                           branch master     branch master  d0be072   302c3dd  1
golang.org/x/text                          v0.3.0            v0.3.0         f21a4df   v0.3.0   14
google.golang.org/genproto                 branch master     branch master  4b56f30   8ac453e  1
google.golang.org/grpc                     ^1.14.0           v1.15.0        8dea3dc   v1.18.0  26
gopkg.in/russross/blackfriday.v2           branch v2         branch v2      6463085   792d134  1
gopkg.in/yaml.v2                           branch v2         branch v2      5420a8b   51d6538  1
```

**Comment by KevinsDeveloper** [comment]
> 我重新clone一份新的，执行 `https_proxy=127.0.0.1:49356 http_proxy=127.0.0.1:49356 dep ensure` 之后，可以正常运行，所有module的版本如下：
> 
> ```
> PROJECT                                    CONSTRAINT        VERSION        REVISION  LATEST   PKGS USED
> github.com/BurntSushi/toml                 v0.3.0            v0.3.0         b26d9c3   v0.3.0   1
> github.com/Joker/jade                      branch master     branch master  8828253   82af6d9  1
> github.com/Shopify/goreferrer              branch master     branch master  b9777dc   ec9c9a5  1
> github.com/asaskevich/govalidator          ^9.0.0            v9             ccb8e96   v9       1
> github.com/aymerick/raymond                branch master     branch master  b565731   b565731  4
> github.com/bitly/go-simplejson             v0.5.0            v0.5.0         aabad6e   v0.5.0   1
> github.com/eknkc/amber                     branch master     branch master  cdade1c   cdade1c  2
> github.com/fatih/structs                   v1.0              v1.0           a720dfa   v1.0     1
> github.com/flosch/pongo2                   branch master     branch master  24195e6   79872a7  1
> github.com/fsnotify/fsnotify               v1.4.7            v1.4.7         c282820   v1.4.7   1
> github.com/go-redis/redis                  ^6.13.2           v6.14.1        f3bba01   v6.15.1  8
> github.com/gobuffalo/packr                 ^1.13.3           v1.13.5        6c8156e   v1.21.9  1
> github.com/golang/protobuf                 v1.2.0            v1.2.0         aa810b6   v1.2.0   5
> github.com/h2non/gock                      ^1.0.9            v1.0.10        db99161   v1.0.12  1
> github.com/hashicorp/go-version            v1.0.0            v1.0.0         b5a281d   v1.0.0   1
> github.com/hashicorp/golang-lru            ^0.5.0            v0.5.0         20f1fb7   v0.5.0   2
> github.com/hashicorp/hcl                   v1.0.0            v1.0.0         8cb6e5b   v1.0.0   10
> github.com/iris-contrib/formBinder         branch master     branch master  ad9fb86   fbd5963  1
> github.com/iris-contrib/go.uuid            branch v2         branch v2      36e9d2e   36e9d2e  1
> github.com/jinzhu/gorm                     ^1.9.1            v1.9.1         6ed508e   v1.9.2   2
> github.com/jinzhu/inflection               branch master     branch master  0414036   0414036  1
> github.com/json-iterator/go                1.1.5 (override)  1.1.5          1624edc   v1.1.5   1
> github.com/juju/errors                     branch master     branch master  22422da   089d3ea  1
> github.com/kataras/golog                   branch master     branch master  03be101   03be101  1
> github.com/kataras/iris                    ^10.7.0           10.7.0         217d9fe   v10.7.1  26
> github.com/kataras/pio                     branch master     branch master  a9733b5   ea782b3  2
> github.com/kataras/survey                  branch v2         branch v2      00934ae   00934ae  3
> github.com/klauspost/compress              v1.4.0            v1.4.0         b939724   v1.4.0   2
> github.com/klauspost/cpuid                 v1.1              v1.1           ae7887d   v1.1     1
> github.com/lib/pq                          ^1.0.0            v1.0.0         4ded0e9   v1.0.0   3
> github.com/magiconair/properties           v1.8.0            v1.8.0         c235336   v1.8.0   1
> github.com/mattn/go-colorable              v0.0.9            v0.0.9         167de6b   v0.0.9   1
> github.com/mattn/go-isatty                 v0.0.4            v0.0.4         6ca4dbf   v0.0.4   1
> github.com/mgutz/ansi                      branch master     branch master  9520e82   9520e82  1
> github.com/microcosm-cc/bluemonday         branch master     branch master  82c7118   506f3da  1
> github.com/mitchellh/mapstructure          v1.0.0            v1.0.0         fa473d1   v1.0.0   1
> github.com/modern-go/concurrent            1.0.3             1.0.3          bacd9c7   1.0.3    1
> github.com/modern-go/reflect2              1.0.1             1.0.1          4b7aa43   1.0.1    1
> github.com/mozillazg/request               ^0.8.0            v0.8.0         052232e   v0.8.0   1
> github.com/oklog/ulid                      ^1.0.0            v1.2.0         6276fb3   v1.3.1   1
> github.com/pelletier/go-toml               v1.2.0            v1.2.0         c01d127   v1.2.0   1
> github.com/pkg/errors                      v0.8.0            v0.8.0         645ef00   v0.8.0   1
> github.com/ryanuber/columnize              branch master     branch master  abc9093   abc9093  1
> github.com/shurcooL/sanitized_anchor_name  branch master     branch master  86672fc   7bfe4c7  1
> github.com/spf13/afero                     v1.1.2            v1.1.2         d40851c   v1.1.2   2
> github.com/spf13/cast                      v1.2.0            v1.2.0         8965335   v1.2.0   1
> github.com/spf13/jwalterweatherman         v1.0.0            v1.0.0         4a4406e   v1.0.0   1
> github.com/spf13/pflag                     v1.0.2            v1.0.2         9a97c10   v1.0.2   1
> github.com/spf13/viper                     ^1.0.2            v1.2.0         8fb6420   v1.3.1   1
> github.com/vicanso/cookies                 ^0.0.2            0.0.2          846aea2   0.0.2    1
> github.com/vicanso/fresh                   ^0.0.2            0.0.2          9d7cefa   0.0.2    1
> github.com/vicanso/keygrip                 0.0.1             0.0.1          c7f2aa0   0.0.1    1
> github.com/vicanso/session                 ^0.0.6            0.0.6          8719544   0.0.8    1
> github.com/vicanso/tiny                    branch master     branch master  cb00b1e   a16c589  1
> go.uber.org/atomic                         v1.3.2            v1.3.2         1ea20fb   v1.3.2   1
> go.uber.org/multierr                       v1.1.0            v1.1.0         3c49374   v1.1.0   1
> go.uber.org/zap                            ^1.0.0-rc.1       v1.9.1         ff33455   v1.9.1   6
> golang.org/x/crypto                        branch master     branch master  0e37d00   c7b33c3  2
> golang.org/x/net                           branch master     branch master  26e67e7   d26f9f9  12
> golang.org/x/sys                           branch master     branch master  d0be072   302c3dd  1
> golang.org/x/text                          v0.3.0            v0.3.0         f21a4df   v0.3.0   14
> google.golang.org/genproto                 branch master     branch master  4b56f30   8ac453e  1
> google.golang.org/grpc                     ^1.14.0           v1.15.0        8dea3dc   v1.18.0  26
> gopkg.in/russross/blackfriday.v2           branch v2         branch v2      6463085   792d134  1
> gopkg.in/yaml.v2                           branch v2         branch v2      5420a8b   51d6538  1
> ```

已解决，非常感谢

**Comment by kataras** [comment]
Hey to all @KevinsDeveloper  @neweyes, @vicanso. Good job here. Sorry for writing at english but I don't know Chinese and I have the solution for you. The problem is that `dep` downloads the stable `pongo2` branch instead of the latest master (which Iris is using on django). 

Here is how you can solve it: https://github.com/kataras/iris/issues/1280#issuecomment-502859266

**Comment by vicanso** [comment]
Thank you for your kindly sharing and have a nice day.
