### ISSUE TITLE
请问这个错误跟iris版本有关系吗？

### ISSUE THREAD

**Issue by KevinsDeveloper** [vicanso/tiny-site#3]
用dep装完又有报错，请问怎么继续了？

# github.com/vicanso/tiny-site/vendor/github.com/kataras/iris/view
vendor/github.com/kataras/iris/view/django.go:225:27: pongo2.RegisterTag(tagName, fn) used as value
vendor/github.com/kataras/iris/view/django.go:253:19: undefined: pongo2.NewLocalFileSystemLoader
vendor/github.com/kataras/iris/view/django.go:258:22: too many arguments in call to pongo2.NewSet
vendor/github.com/kataras/iris/view/django.go:311:22: too many arguments in call to pongo2.NewSet
        have (string, *tDjangoAssetLoader)
        want (string)

**Comment by KevinsDeveloper** [comment]
已解决

**Comment by neweyes** [comment]
我也遇到了这个问题，请问你是怎么解决的
